[package]
name = "achronyme-types"
version = "0.6.6"
edition = "2021"

[dependencies]
achronyme-parser = { path = "../achronyme-parser" }
tokio = { version = "1.41", features = ["sync", "rt"] }
futures = "0.3"
parking_lot = "0.12"
